name: Build for iOS
description: "Build V8 for iOS"

inputs:
  archive-name:
    description: "Base name of the archive to create"
    default: v8_iOS
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Restore CCache
      uses: actions/cache@v3
      with:
        path: .ccache
        key: ${{ runner.os }}:libv8:ccache:${{ github.run_number }}
        restore-keys: |
          ${{ runner.os }}:libv8:ccache:

    - name: Install the Apple certificate
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

    - name: Setup Python 2.7
      uses: MatteoH2O1999/setup-python@v2
      with:
        python-version: "2.7"

    - name: Setup Build Tools
      shell: bash
      run: |
        brew install nutcracker/tap/openssl@1.0
        brew install ninja ccache

        echo "$(brew --prefix ccache)/libexec" >> "$GITHUB_PATH"
        echo "CCACHE_CPP2=yes" >> "$GITHUB_ENV"
        echo "CCACHE_SLOPPINESS=time_macros" >> "$GITHUB_ENV"

        ccacheDir="${GITHUB_WORKSPACE}/.ccache"
        test -d "$ccacheDir" || mkdir "$ccacheDir"

        echo "CCACHE_DIR=$ccacheDir" >> "$GITHUB_ENV"

    - name: Download V8 Source
      shell: bash
      run: ./v8_download.sh

    - name: Compile V8
      shell: bash
      run: ./v8_compile.sh "iOS"

    - name: Show CCache Status
      shell: bash
      run: ccache -s

    - name: Test V8
      continue-on-error: true
      shell: bash
      run: ./v8_test.sh

    - name: Archive V8
      shell: bash
      run: ./archive.sh ${{ inputs.archive-name }}
