name: V8 Build Test

on:
  push:
    branches:
      - master
      - actions
      - build-*
    paths-ignore:
      - "depot_tools"
      - ".gitignore"
      - ".gitpod*"

jobs:
  build-test:
    name: Build V8
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Restore V8 Cache
        uses: actions/cache@v3
        with:
          path: |
            v8
            .gclient_entries
            .gclient_previous_sync_commits
            .cipd
          key: ${{ runner.os }}:libv8:v8:${{ hashFiles('**/VERSION') }}

      - name: Build V8 for Linux
        if: startsWith(matrix.os, 'ubuntu')
        uses: ./.github/actions/build-linux
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Build V8 for macOS
        if: startsWith(matrix.os, 'macos')
        uses: ./.github/actions/build-macos
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Build V8 for Windows
        if: startsWith(matrix.os, 'windows')
        uses: ./.github/actions/build-windows
        with:
          archive-name: v8_${{ runner.os }}_amd64

      - name: Archive V8 Library
        uses: actions/upload-artifact@v3
        with:
          path: |
            *.tar.xz
            *.7z
          retention-days: 7
